

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=OrderService

server.port=8083
eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
spring.application.name = order-service


razorpay.api.key=${RAZORPAY_API_KEY:}
razorpay.api.secret=${RAZORPAY_API_SECRET:}
razorpay.currency=INR
razorpay.company.name=CropDeal
