
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=InventoryService

server.port=8082
eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
spring.application.name = inventory-service

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#okta.oauth2.issuer=https://dev-67047085.okta.com/oauth2/default
#okta.oauth2.audience=api://default