

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=UserService

spring.main.allow-bean-definition-overriding=true

server.port=8081
eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
spring.application.name = user-service


#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-67047085.okta.com/oauth2/default
#
#spring.security.oauth2.client.provider.okta.issuer-uri=https://dev-67047085.okta.com/oauth2/default
#
#spring.security.oauth2.client.registration.my-internal-client.provider=okta
#spring.security.oauth2.client.registration.my-internal-client.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.my-internal-client.scope=internal
#spring.security.oauth2.client.registration.my-internal-client.client-id=0oa9v8il14MJsgjqN5d7
#spring.security.oauth2.client.registration.my-internal-client.client-secret=k23fhJpieLPQdNf3U15RUUPDlyuU9XkFDHMu33sE
#
#
#okta.oauth2.scopes=openid, profile, email, offline_access
#okta.oauth2.issuer=https://dev-67047085.okta.com/oauth2/default
#okta.oauth2.client-id=0oa9v8il14MJsgjqN5d7
#okta.oauth2.client-secret=k23fhJpieLPQdNf3U15RUUPDlyuU9XkFDHMu33sE
#okta.oauth2.api-token=00T146lz96jCxoYKY5d7
#okta.oauth2.audience=api://default
#okta.org-url=https://dev-67047085.okta.com
