

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=OrderService

server.port=8083
eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
spring.application.name = order-service


#razorpay.api.key=rzp_test_tTLe3XRUKXz0UV
#razorpay.api.secret=j5oLXmPeUJK8nN00naA5VFID
#razorpay.currency=INR
#razorpay.company.name=Jesmin
